env:
  global:
    - PATH=$HOME/.local/bin:$PATH
matrix:
  include:
    - stage: build
      language: haskell
      before_install:
        # Download and unpack the stack executable
        - mkdir -p ~/.local/bin
        - export PATH=$HOME/.local/bin:$PATH
        - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
        - npm install -g lessc
      script:
        - scripts/build.sh
    - stage: deploy
      script:
        - scripts/deploy_master.sh
    - stage: acceptance-test
      sudo: false
      language: python
      dist: xenial
      python: 3.7
      install:
        - npm install -g allure-commandline
        - travis_retry pip install -q -r requirements.txt
      script:
        - behave
